import type { Metadata } from "next";
import { clashDisplayFont, hkGuiseFont } from "@/lib/fonts";
import clsx from "clsx";
import { GQlProvider } from "@/providers/gql-provider";
import { WagmiProvider } from "@/providers/wagmi-provider";
import { ConnectButton } from "@/components/connect-button";
import { Header, Page } from "@/components/layout-components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(clashDisplayFont.variable, hkGuiseFont.variable)}
    >
      <body>
        <WagmiProvider>
          <GQlProvider>
            <Page header={<Header isBlurred rightSlot={<ConnectButton />} />}>
              {children}
            </Page>
          </GQlProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
