import type { Metadata } from "next";
import { clashDisplayFont, hkGuiseFont } from "@/lib/fonts";
import clsx from "clsx";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(clashDisplayFont.variable, hkGuiseFont.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
